language: cpp
os: linux
dist: trusty
sudo: required

python:
    - "2.7"
    - "3.5"
before_install:
  - wget http://sourceforge.net/projects/devkitpro/files/Automated%20Installer/devkitARMupdate.pl
  - export DEVKITPRO=/home/travis/devkitPro
  - export DEVKITARM=${DEVKITPRO}/devkitARM

install:
  - sudo perl devkitARMupdate.pl  
  - wget --no-check-certificate https://codeload.github.com/smealum/ctrulib/zip/master -O /tmp/ctrulib.zip
  - unzip /tmp/ctrulib.zip
  - cd ctrulib-master/libctru
  - make && sudo make install
  - cd ../..
  - wget --no-check-certificate https://codeload.github.com/fincs/citro3d/zip/next -O /tmp/citro3d.zip
  - unzip /tmp/citro3d.zip
  - cd citro3d-next
  - make && sudo make install
  - cd ..  
  - wget --no-check-certificate https://github.com/xerpi/3ds_portlibs/releases/download/1/portlibs-linux.zip -O /tmp/3ds_portlibs.zip
  - unzip /tmp/3ds_portlibs.zip
  - sudo cp -R portlibs ${DEVKITPRO}/
  - wget --no-check-certificate https://codeload.github.com/xerpi/sf2dlib/zip/master -O /tmp/sf2dlib.zip
  - unzip /tmp/sf2dlib.zip
  - cd sf2dlib-master/libsf2d
  - make && sudo make install
  - cd ../..
  - wget --no-check-certificate https://codeload.github.com/xerpi/sfillib/zip/master -O /tmp/sfillib.zip
  - unzip /tmp/sfillib.zip
  - cd sfillib-master/libsfil
  - make && sudo make install
  - cd ../..
  - wget --no-check-certificate https://codeload.github.com/xerpi/sftdlib/zip/master -O /tmp/sftdlib.zip
  - unzip /tmp/sftdlib.zip
  - cd sftdlib-master/libsftd
  - make && sudo make install
  - cd ../..
  - wget --no-check-certificate  https://raw.githubusercontent.com/libretro/RetroArch/master/ctr/tools/bannertool-linux
  - chmod 777 bannertool-linux
  - sudo cp bannertool-linux /usr/bin/bannertool
  - wget --no-check-certificate  https://raw.githubusercontent.com/libretro/RetroArch/master/ctr/tools/makerom-linux
  - chmod 777 makerom-linux
  - sudo cp makerom-linux /usr/bin/makerom
  - wget --no-check-certificate https://codeload.github.com/ahezard/libnds/zip/master -O /tmp/libnds.zip
  - unzip /tmp/libnds.zip
  - cd libnds-master
  - make && sudo make install
  - pip3 install requests
  - cd ..  
script:
  - echo "Starting compilation"
  - cd twlnand-stage1
  - echo "Compiling TWLoader NAND Side Stage 1"
  - make
  - cd ..
  - cd twlnand-stage2
  - echo "Compiling TWLoader NAND Side Stage 2"
  - make
  - cd ..
  - echo "Compiling TWLoader GUI"
  - cd gui
  - make -j8 COMPILE_3DSX=0
  - cd ..
  - echo "Creating release ZIP"
  - mkdir "Nightly"
  - cd "twlnand-stage2"
  - cp "Stage2.nds" "../Nightly/TWLD.twldr"
  - cd ..
  - cd gui
  - cp "TWLoader.cia" "../Nightly/TWLoader.cia"
  - cd ..
  - cd "Nightly"
  - zip "TWLoader.zip" *
  - dir
  - cd ..
  - echo "Compilation ended"
after_success:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then python3 upload-nightly.py; fi'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
    - libstdc++6
    - lftp
env:
  matrix:
    secure: mm0UyPlPqsswnelgQhXYop0+KUEUc3HaAKBvftyM8t6iHJdhoa9uSpYcc/muAdsdXGoC99obLlGhAZQBfNXc6WmTlujK9MWEg1JGY2bEQH02T/dmxMI8Jf+McfxyHK3XY0eHSC6YOXiI1SXeNWv0kw6GK7dGWks/aujBEuN+w4S9zU1zn68Us98lE5BfOfi2goEiiN6z1P1SqxbnoDpGIfM3KlBH7a8S7jhzQmTz01JwHv0rcySYdMUN+JM31U6vi4ccd9cvQDlXUwNDvEC2pMqMl3E8JbGmSs3PDizySIciZC4CnAY+dqJYRHSUxqBYNlYeq4sg7aLJIvalQVtz6UlbgjCjPcBTh6WRaRrrAZ7lxZfle0jnSwTv8PwJhcnASr3l0EfDRXLq+nBgjOldN29W7zFP5wZadGCSsIvOVcb6kvi5rQeBIzQ02wNoXh2l+dA9fLVQpxX4gxzzU0WLwVWvDIP+50FxrLlMjqjbPIFmu0Qqc36USruKkDLN83YftuH5e7j8KtGfayiZspUVC8BdUcRIw8In3pn9xuw357sWXvLN7hC7Nu+IUb+/pElypurWo7Kz8ymc3kzRSeHaAksNyD8TzGRIpl4gjuE96LCG4bqTa2kl+XHenJUJw8gTqQ9oXi2nsndheWyinMkxpkHUmfrpqMBfFBxf82xOgFU=